### ISSUE TITLE
Make prom-client a peer dependency

### ISSUE THREAD

**Issue by voxpelli** [roylines/node-epimetheus#15]
To make it easier to add additional metrics from outside this module it would be good if this module like eg. https://github.com/SimenB/node-prometheus-gc-stats added `prom-client` as a peer-dependency rather than as an ordinary dependency.

Reason for doing so is that it is important that all modules that interacts with the `prom-client` module are interacting with the same instance of the module and this will only happen if they all require the same installed modules – and the only way to really guarantee that is to have all modules require the dependency of the top project.

With the current setup there will be multiple instances of `prom-client` if the different modules have different version requirements from `prom-client` or if someone uses npm 2 or for some other reason doesn't flatten the dependency tree.

**Comment by JohnieLee** [comment]
+1 on this.

I just encountered this issue where I was collecting additional metrics using prom-client but it wasn't showing up in /metrics.  It turned out that nodejs module cache had two different prom-clients (one from epimetheus and one from my direct dependency).  With such a core metrics instrumentation library, everyone need to play nice.

Here is a similar scenario on submodule dependency: http://justjs.com/posts/singletons-in-node-js-modules-cannot-be-trusted-or-why-you-can-t-just-do-var-foo-require-baz-init

**Comment by JohnieLee** [comment]
I've submitted a pull request for this change: https://github.com/roylines/node-epimetheus/pull/19

**Comment by ergh99** [comment]
I believe this breaks the example.  Here's an output snippet from running docker-compose up:
```
restify_1     | module.js:472
restify_1     |     throw err;
restify_1     |     ^
restify_1     | 
restify_1     | Error: Cannot find module 'prom-client'
restify_1     |     at Function.Module._resolveFilename (module.js:470:15)
restify_1     |     at Function.Module._load (module.js:418:25)
restify_1     |     at Module.require (module.js:498:17)
restify_1     |     at require (internal/module.js:20:19)
restify_1     |     at Object.<anonymous> (/src/node_modules/epimetheus/lib/metrics.js:1:78)
```

**Comment by errordeveloper** [comment]
It is a peer dependency now (see #19), I think this issue can be closed.
